# Generated by Django 5.0.1 on 2024-02-21 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('session_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('conversation', models.CharField(max_length=1000000)),
            ],
        ),
    ]
