# Generated by Django 5.0.1 on 2024-02-22 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='round',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='history',
            name='turn',
            field=models.CharField(default='preflop', max_length=10),
        ),
        migrations.AlterField(
            model_name='history',
            name='conversation',
            field=models.CharField(default='', max_length=1000000),
        ),
    ]
