# Generated by Django 5.0.1 on 2024-03-08 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_history_round_history_turn_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
